---
title: "2027449 - PERCEPCION REMOTA AVANZADA"
subtitle: "Academic Year: 2026"
format: html
---
## PREREQUISITOS:
- Aprobación del curso *Percepción Remota*
- Aprobación del curso *Programación SIG*

## DESCRIPCIÓN DE LA ASIGNATURA:
::: {.callout-important collapse=false}
### OBJETIVOS:
- Conocer nuevos conceptos y técnicas de análisis de datos de percepción remota
-	Profundizar en tópicos avanzados  de percepción remota de la superficie terrestre 
-	Entender los conceptos básicos de *deep learning* aplicado a datos de observación terrestre
-	Aplicar métodos y técnicas de *deep learning* para obtener información temática a partir de imágenes ópticas y SAR

### COMPETENCIAS GENÉRICAS: 
-	Comprensión de los fundamentos teóricos de la percepción remota de la superficie terrestre
-	Obtención de habilidades computacionales para seleccionar, procesar y analizar imágenes
-	Desarrollo de pensamiento crítico sobre las ventajas y las limitaciones de diferentes técnicas

### COMPETENCIAS ESPECÍFICAS:
- Entendimiento del flujo de trabajo genérico  de percepción remota
- Adaptación y creación de scripts para  procesamiento y análisis de imágenes
-	Entendimiento de los conceptos fundamentales de deep learning aplicado a percepción remota

### METODOLOGIA:
-	Lectura antes de la clase a cargo del estudiante
- Presentación de conceptos, métodos y técnicas a cargo del profesor
-	Realización de ejercicios prácticos y elaboración de reportes técnicos a cargo  del estudiante

### SOFTWARE
-   Python & Jupyter notebooks & Google Colaboratory

### USO DE INTELIGENCIA ARTIFICIAL

Los estudiantes pueden usar herramientas de  Inteligencia Artifical  como un apoyo, y no como un sustituto, del pensamiento, el esfuerzo y el estilo personal. En este curso se permite el uso de IA generativa hasta un máximo del 50 % de cada trabajo presentado.

### ASISTENCIA OBLIGATORIA



:::


## CONTENIDO DETALLADO 

::: {.callout-important collapse=true}

### Unidad 1 –  Percepción remota multi-espectral

### Unidad 2 -  Percepción remota hiper-espectral 

### Unidad 3 -  Percepción remota termal

### Unidad 4 – Principios de aprendizaje profundo 

### Unidad 5 –  Redes neuronales convolucionales 

### Unidad 6 – Aprendizaje autosupervisado 

### Unidad 7 – Segmentación semántica

### Unidad 8 - Modelos fundamentales para datos geoespaciales

:::


## EVALUACIÓN DEL CURSO: 

::: {.callout-important collapse=false}

-	Presentación de dos exámenes teóricos (50%)
    - Examen 1 - 14 de Octubre
    - Examen 2 - 2 de Diciembre
-	Entrega de dos informes técnicos  (50%)
    - Informe 1 - 21 de Octubre
    - Informe 2 - 9 de Diciembre

:::

## BIBLIOGRAFIA

::: {.callout-important collapse=true}

Chollet, F. Deep Learning with Python [2nd ed.],  Manning, 2021. 504 pp.

Corley, I., Lehmann, N., Robinson, C., Tseng, G., Fuller, A., Alemohammad, H., Shelhamer, E., Marcus, J., and Kerner, H.  No One Knows the State of the Art in Geospatial Foundation Models. 2026. https://arxiv.org/html/2605.12678v1

Gao, S., Hu, Y., and Li, W. Handbook of Geospatial Artificial Intelligence. CRC Press. 2024. 468 pp.

Lunga D. and Hänsch, R. GeoAI for Earth Observation Imagery: Fundamentals and Practical Applications. Elsevier. 2026. 501 pp.

Mayer, T., Bhandari, B., and Saah, D. Applied Artificial Intelligence and Deep Learning Book. 2026. https://zenodo.org/records/20547797

Raff, E. Inside Deep Learning – Math, Algorithms, Models,  Manning, 2022. 565 pp.

Rees, W.G. Physical Principles of Remote Sensing [3rd ed.],  Cambridge University Press, 2012. 494 pp.

Richards, J.A. Remote Sensing Digital Image Analysis Sensing [6th ed.], Springer, 2022. 567 pp.

Ustin, S.L., and Middleton E.M. Current and near-term advances in Earth observation for ecological applications. Ecological Processes, 2021, 10:1 

Wu, Q. GeoAI with Python: A Practical Guide to Open-Source Geospatial AI, Qiusheng Wu , 2026. 430 pp. https://book.opengeoai.org/

:::
