---
title: "2027449 - PERCEPCION REMOTA AVANZADA"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# 📑 Course Brief

**Focus:** the focus of this course is to gain knowledge for developing novel remote sensing analysis workflows.

**How:** reading,  learning by doing and writing

# 🎯 Learning Objectives

- Appraise the process of image analysis and its relation to research.
- Dive deep into the physical principles of multispectral remote sensing. 
- Distinguish the main principles of deep learning for Earth Observation data.
- Apply AI techniques  to obtain thematic information from Earth Observation data.

# Class Atendance Policy

Students are expected to attend all classes. Occasional absences due to illness are considered excused. Participation in university activities must be requested in advance.

# Artificial Intelligence Policy

Students may use generative AI to support —not replace— their own thinking, effort, and style. In any case, the use of generative AI is permitted for up to 50% of the submitted work.

-----------------

**Select Academic Year/Term:**

<a href="2026/index.qmd">
    <button class="button-61">2026</button>
</a>

